version: '3.8'

services:
  web:
    build: .
    ports:
      - "8501:8501"
    container_name: runnershop
    volumes:
      - .:/app
    networks:
      - chatbot

networks:
  chatbot:
    driver: bridge
